apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.api.name }}-deployment"
  namespace: "{{ .Values.app.name }}-namespace"
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.api.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.api.components }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image }}:{{ .Values.api.version }}"
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            {{- range .Values.api.env }}
            {{- $data := dict "name" $.Values.rabbitmq.name "env" . }}
            {{- include "env.template" $data | indent 12 }}
            {{- end }}
          resources: {{ .Values.api.limits | toYaml | nindent 14 }}
          volumeMounts:
            - name: "{{ .Values.api.name }}-data"
              mountPath: /opt/app/uploads
      volumes:
        - name: "{{ .Values.api.name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Values.api.name }}-pvc"
