apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: "{{ .Values.app.name }}-namespace"
  labels:
    name: myingress
  annotations:
    # добавляется базовый путь к возвращаемым html
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: conv.test
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "{{ .Values.app.name }}-clusterip"
                port:
                  number: {{ .Values.app.port }}
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: "{{ .Values.api.name }}-clusterip"
                port:
                  number: {{ .Values.api.port }}
