apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.rabbitmq.name }}-clusterip"
  namespace: "{{ .Values.app.name }}-namespace"
spec:
  type: ClusterIP
  selector:
    components: {{ .Values.rabbitmq.components }}
  ports:
    - port: {{ .Values.rabbitmq.port }}
      protocol: TCP
