apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.rabbitmq.name }}-secret"
  namespace: "{{ .Values.app.name }}-namespace"
type: Opaque
data:
  SEED_USERNAME: {{ .Values.stack.SEED_USERNAME | b64enc }}
  SEED_USER_PASSWORD: {{ .Values.stack.SEED_USER_PASSWORD | b64enc }}
  AMQP_EXCHANGE: {{ .Values.stack.AMQP_EXCHANGE | b64enc }}
  AMQP_USER: {{ .Values.stack.AMQP_USER | b64enc }}
  AMQP_PASSWORD: {{ .Values.stack.AMQP_PASSWORD | b64enc }}
  AMQP_HOSTNAME: {{ .Values.stack.AMQP_HOSTNAME | b64enc }}
  AMQP_QUEUE: {{ .Values.stack.AMQP_QUEUE | b64enc }}
