stack:
    SEED_USERNAME: ENC[AES256_GCM,data:0q7bfA==,iv:XLbWmkFLBsBR2IC/V7EXPDsCLv8Rn0q28SV4H4kRr8g=,tag:8IcfW8fPsGYyozNh+GJ6pA==,type:str]
    SEED_USER_PASSWORD: ENC[AES256_GCM,data:zXUrNQ==,iv:Yct4mEBwZOSQOk2YS8z3g8yxWrPmybn6Xoyk2H8BvqE=,tag:ofNFyYOxubdi+71th+Tj2w==,type:str]
    AMQP_EXCHANGE: ENC[AES256_GCM,data:ePMj3pxdL64=,iv:bz5nuFlxrNEtWuYTgFeFO2hRviM41ibNjM5U7B0x0kI=,tag:0xSLXt7knLnDh6/3OR4Uxg==,type:str]
    AMQP_USER: ENC[AES256_GCM,data:kweeUA==,iv:EZReprkYzA4KlzLuFDyPwzIkcl8WgRv8b75wUtm76+0=,tag:4DLFGC/vJQdmBDNzWnfdRg==,type:str]
    AMQP_PASSWORD: ENC[AES256_GCM,data:feq6QA==,iv:FpTO5H0lLMWj9s1NaSbGpi8OYMWwVXrX744VYdb/uAI=,tag:5EkrwtL21Qe34voqpFqS2Q==,type:str]
    AMQP_HOSTNAME: ENC[AES256_GCM,data:XUQaw/bJb/ViZ5PgP6HIML48,iv:S5BFOg9otnM+R6xXa3S+TWW6J4RLRhJkBJ6ScXTrFHU=,tag:ualcHh6CrFXDZo6K3WVpdQ==,type:str]
    AMQP_QUEUE: ENC[AES256_GCM,data:mwWSkZhJUb6h,iv:em4fva2XE7F3MJOnh1U2jVIfpCvNkgj7+5eIZbflTmY=,tag:1Uh0Sjt3F3tWrGLHXxUggg==,type:str]
sops:
    lastmodified: "2025-11-03T11:06:27Z"
    mac: ENC[AES256_GCM,data:ZRxc5m/yxwrqcFaMEmZX1CSDRMBXhHfwv6kDns3jTHv3+CHhQpAElUd9/jWs5LKLPOChTr2SjovthRzaKWxAjfzhDA2aELJU1NbCaYV2FWjZVf+F1rUwq46OxbXcWajrF3iSkTbryvgX9TgnlXWftbye1p8uF36+klhL+Zler90=,iv:r90Hnf1PMFJIYVuKumFu9XQACXVeU/W08vNu1aq9dy0=,tag:yLEVV8HCfgpyOjiiA6JAVw==,type:str]
    pgp:
        - created_at: "2025-11-03T11:06:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8uYC06rubkMSAQdA4RqHPWUJLWuwMrK15vy2HujvhH/kUbGgX7cRjWJYVRkw
            3l4H4VbLzmWFzSzoaG8kiqYblIjkL9EQUsBK6m9RbR+ZqgVzo9FLHeDnlklPAZgI
            1GgBCQIQ3WveuxPgo22wq5V+lGXFZpDiiHc1oi9R7vlE+bqnsAwq8+Yk6Q7bBb/N
            jlwM5SzHrAvVjzvU95ozjTRR85PgCTfYjUV+6TKFOrvB3wmz5gC9vaTar/uXwSnI
            EHWoBMkzJNepZw==
            =xX2H
            -----END PGP MESSAGE-----
          fp: 7C5BA6E0A3D869E63F88A422AA8F1183338074A7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
