app:
  name: converter
  version: 1.2
  components: frontend
  image: antonlarichev/conv-app
  port: 80
  replicas: 1
  limits:
    memory: 512Mi
    cpu: 500m
  domain: conv.test
api:
  name: converter-api
  port: 3000
