app:
  name: converter
  version: 1.2
  components: frontend
  image: antonlarichev/conv-app
  port: 80
  replicas: 1
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 512Mi
    cpu: 500m
  domain: conv.test

api:
  name: converter-api
  version: 1.0
  port: 3000
  components: backend
  image: antonlarichev/conv-api
  replicas: 1
  limits:
    memory: 512Mi
    cpu: 500m
  env:
    - AMQP_EXCHANGE
    - AMQP_USER
    - AMQP_PASSWORD
    - AMQP_HOSTNAME
    - AMQP_QUEUE

rabbitmq:
  name: rabbitmq
  version: 4.1.4-management
  port: 5672
  components: rabbitmq
  image: rabbitmq
  limits:
    memory: "2Gi"
    cpu: "300m"
  env:
    - SEED_USERNAME
    - SEED_USER_PASSWORD
